# #########################################################################
#
#   Control Table constants for Dynamixel XL330-M288-T
#   E-manual has descriptions of each data in the control table and value ranges
#   E-manual Link: https://emanual.robotis.com/docs/en/dxl/x/xl330-m288/
#
# #########################################################################


# EEPROM AREA (ONLY WRITE-ABLE WITH TORQUE OFF)

ADDR_DRIVE_MODE = 10
LEN_DRIVE_MODE = 1

ADDR_OPERATING_MODE = 11
LEN_OPERATING_MODE = 1

ADDR_HOMING_OFFSET = 20
LEN__HOMING_OFFSET = 4

ADDR_MOVING_THRESHOLD = 24
LEN_MOVING_THRESHOLD = 4

ADDR_TEMP_LIMIT = 31
LEN_TEMP_LIMIT = 1

ADDR_MAX_VOLTAGE_LIMIT = 32
LEN_MAX_VOLTAGE_LIMIT = 2

ADDR_MIN_VOLTAGE_LIMIT = 32
LEN_MIN_VOLTAGE_LIMIT = 2

ADDR_PWM_LIMIT = 36
LEN_PWM_LIMIT = 2

ADDR_CURRENT_LIMIT = 38
LEN_CURRENT_LIMIT = 2

ADDR_VELOCITY_LIMIT = 44
LEN_VELOCITY_LIMIT = 4

ADDR_MAX_POSITION_LIMIT = 48
LEN_MAX_POSITION_LIMIT = 4

ADDR_MIN_POSITION_LIMIT = 52
LEN_MIN_POSITION_LIMIT = 4

ADDR_PWM_SLOPE = 62
LEN__PWM_SLOPE = 1

ADDR_SHUTDOWN = 63
LEN_SHUTDOWN = 1


# RAM AREA, WRITE/READ ALWAYS

ADDR_TORQUE_ENABLE = 64
LEN_TORQUE_ENABLE = 1

ADDR_STATUS_RETURN_LEVEL = 68
LEN_STATUS_RETURN_LEVEL = 1

ADDR_REGISTERED_INSTRCT = 69
LEN_REGISTERED_INSTRCT = 1

ADDR_HARDWARE_ERROR = 70
LEN_HARDWARE_ERROR = 1

ADDR_VELOCITY_I_GAIN = 76
LEN_VELOCITY_I_GAIN = 2

ADDR_VELOCITY_P_GAIN = 78
LEN_VELOCITY_P_GAIN = 2

ADDR_POSITION_D_GAIN = 80
LEN_POSITION_D_GAIN = 2

ADDR_POSITION_I_GAIN = 82
LEN_POSITION_I_GAIN = 2

ADDR_POSITION_P_GAIN = 84
LEN_POSITION_P_GAIN = 2

ADDR_FEEDFRWRD_2ND_GAIN = 88
LEN_FEEDFRWRD_2ND_GAIN = 2

ADDR_FEEDFRWRD_1ST_GAIN = 90
LEN_FEEDFRWRD_1ST_GAIN = 2

ADDR_GOAL_PWM = 100
LEN_GOAL_PWM = 2

ADDR_GOAL_CURRENT = 102
LEN_GOAL_CURRENT = 2

ADDR_GOAL_VELOCITY = 104
LEN_GOAL_VELOCITY = 4

ADDR_PROFILE_ACCELERATION = 108
LEN_PROFILE_ACCELERATION = 4

ADDR_PROFILE_VELOCITY = 112
LEN_PROFILE_VELOCITY = 4

ADDR_GOAL_POSITION = 116
LEN_GOAL_POSITION = 4

ADDR_MOVING = 122
LEN_MOVING = 1

ADDR_MOVING_STATUS = 123
LEN_MOVING_STATUS = 1

ADDR_PRESENT_PWM = 124
LEN_PRESENT_PWM = 2

ADDR_PRESENT_CURRENT = 126
LEN_PRESENT_CURRENT = 2

ADDR_PRESENT_VELOCITY = 128
LEN_PRESENT_VELOCITY = 4

ADDR_PRESENT_POSITION = 132
LEN_PRESENT_POSITION = 4

ADDR_VELOCITY_TRAJ = 136
LEN_VELOCITY_TRAJ = 4

ADDR_POSITION_TRAJ = 140
LEN_POSITION_TRAJ = 4

ADDR_PRESENT_INPUT_VOLTAGE = 144
LEN_PRESENT_INPUT_VOLTAGE = 2

ADDR_PRESENT_TEMP = 146
LEN_PRESENT_TEMP = 1
